#!/usr/bin/env python

from __future__ import print_function

import getopt
import sys
import os
import base64

import w4af.core.controllers.output_manager as om

def _configure_output_manager():
    """
    Make sure that the output manager is started before doing anything else,
    since it is used by most w4af modules
    """
    try:
        om.manager.set_output_plugins(['console'])
    except Exception as e:
        print('Something went wrong, w4af failed to start the output manager.')
        print('Exception: "%s"' % e)
        sys.exit(-9)


def usage():
    print(USAGE_DOC)


def main():
    from w4af.core.ui.api.main import main
    sys.exit(main(launch_gui=True, interface_name="Web Interface"))

def _main():
    _configure_output_manager()
    sys.exit(main())


if __name__ == "__main__":
    _main()
